### ISSUE TITLE
Manifest includes name-associated dates as name in metadata

### ISSUE THREAD

**Issue by bencomp** [LeidenUniversityLibrary/islandora_iiif_manifests#20]
In a manifest for a work with one author with dates associated to the name, these dates show up as a separate author/creator in the list of metadata fields. I think the dates should either be ignored or appended to the actual name field.

![Screenshot 2020-07-17 at 11 12 32](https://user-images.githubusercontent.com/1303898/87769843-75d9bf00-c81e-11ea-9fb0-d82d6089f02d.png)

**Comment by lucasvanschaik** [comment]
Solved in #22
