### ISSUE TITLE
Date in metadata generated as number instead of string

### ISSUE THREAD

**Issue by bencomp** [LeidenUniversityLibrary/islandora_iiif_manifests#21]
In <https://digitalcollections.universiteitleiden.nl/iiif_manifest/item:1938202/manifest>, the *Date issued* metadata field has a numeric value, although the specification requires all metadata fields to have a string value (or a language-tagged value).

Mirador doesn't understand the year-as-number:

![Screenshot 2020-07-17 at 11 26 04](https://user-images.githubusercontent.com/1303898/87771261-678ca280-c820-11ea-9953-ef6f985cb435.png)

**Comment by lucasvanschaik** [comment]
Might remove the JSON_NUMERIC_CHECK ?
https://github.com/LeidenUniversityLibrary/islandora_iiif_manifests/blob/66b64c100f75ee0eead172a22c58a4e45ee6fea8/includes/manifest.inc#L78

**Comment by lucasvanschaik** [comment]
Solved in d517aa7958caa788a7602e8dab54ea970ef63f3e
