### ISSUE TITLE
No manifest found should be JSON and HTTP 404

### ISSUE THREAD

**Issue by bencomp** [LeidenUniversityLibrary/islandora_iiif_manifests#38]
When I request a Manifest that doesn't exist, like <https://digitalcollections.universiteitleiden.nl/iiif_manifest/item:1895/manifest>, Islandora gives me an HTTP 400 response with plain text "No manifest found". The content type of the response says it is JSON, so Firefox tries and fails to parse the response.

I think it would be good to serve JSON in an HTTP 404 response, e.g.:

```json
{"error": "No manifest available"}
```

**Comment by ublrama** [comment]
I have updated the code to return a HTTP 404 and a JSON format response. Can you please confirm that this issue can be closed?

https://github.com/LeidenUniversityLibrary/islandora_iiif_manifests/commit/8ac29de2053060dcead70f7cd35e495144f13017

**Comment by bencomp** [comment]
That works! Maybe before closing, you want to update line 35 too? I didn't see 403 errors, but the code suggests that it wouldn't be valid JSON either. How about:
```json
{"error": "Access to this resource was denied"}
```

**Comment by ublrama** [comment]
I have update the code, though I cannot thoroughly test this.  https://github.com/LeidenUniversityLibrary/islandora_iiif_manifests/commit/9142c1e70aa8d6f0c733e6f9f240d52c5525268c

**Comment by bencomp** [comment]
Looks good to me :)
